# .github/workflows/frogbot.yml

name: "JFrog Frogbot Scan"

on:
  pull_request:  # Trigger on pull requests
  workflow_dispatch:  # Manual trigger

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Frogbot Scan
        uses: jfrog/frogbot@v2.23.2
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}